[package]
name = "Davenstein"
version = "0.15.6"
edition = "2024"

[lib]
name = "davelib"
path = "src/lib.rs"

[[bin]]
name = "Davenstein"
path = "src/main.rs"
doc = false

[[bin]]
name = "pak_builder"
path = "src/pak_builder.rs"

[dependencies]
bevy = { version = "0.18", features = ["wav", "debug"] }
dirs = "6"
futures-lite = "2"
memmap2 = "0.9"
rand = "0.10"
ron = "0.12"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
