[package]
name = "Davenstein"
version = "0.11.5"
edition = "2024"

[lib]
name = "davelib"
path = "src/lib.rs"

[[bin]]
name = "Davenstein"
path = "src/main.rs"
doc = false

[dependencies]
bevy = { version = "0.18", features = ["wav"] }
dirs = "6"
include_dir = "0.7"
rand = "0.10"
ron = "0.12"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
