[package]
name = "Davenstein"
version = "0.9.21"
edition = "2024"

[lib]
name = "davelib"
path = "src/lib.rs"

[[bin]]
name = "Davenstein"
path = "src/main.rs"
doc = false

[dependencies]
bevy = "0.17"
include_dir = "0.7"
rand = "0.9"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
