[target.armv7-unknown-linux-gnueabihf]
pre-build = [
  "dpkg --add-architecture armhf && apt-get update && apt-get install -y --no-install-recommends pkg-config libwayland-dev:armhf libasound2-dev:armhf libudev-dev:armhf && rm -rf /var/lib/apt/lists/*"
]
